import Navbar from './Navbar'
//import { Footer } from './Footer'
import { Children, ReactNode, useEffect, useState } from 'react';
import styles from '@/styles/Home.module.css'
import Head from 'next/head';
import Sidebar from './Sidebar';
import { useRouter } from 'next/router';

type LayoutProps = {
  children: ReactNode;
  idioma: string;
  setIdioma: React.Dispatch<React.SetStateAction<string>>;
  darkMode: string;
  setDarkMode: React.Dispatch<React.SetStateAction<string>>;
}


export default function Layout({ children, idioma, setIdioma, darkMode, setDarkMode }: LayoutProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [pageTitle, setPageTitle] = useState('Juank Todo App');
  const router = useRouter();

  const toggleSidebar = () => {
    setIsOpen(!isOpen)
  }

  useEffect(() => {
    const handleRouteChange = (url: string) => {
      const newPageTitle = getPageTitle(url);
      setPageTitle(newPageTitle);
    };

    setPageTitle(getPageTitle(router.asPath));

    router.events.on('routeChangeComplete', handleRouteChange);

    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events, router.asPath]);

  const getPageTitle = (url: string) => {
    const pageTitle = url === "/" ? "Juank Todo App" : url.substring(1); // Eliminar el slash si el url es "/" o quitar el primer carácter (el slash) en otros casos
    const capitalizedPageTitle = pageTitle.charAt(0).toUpperCase() + pageTitle.slice(1); // Hacer mayúscula la primera letra y convertir el resto a minúsculas
      return capitalizedPageTitle;
  };

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar idioma={idioma} setIdioma={setIdioma} darkMode={darkMode} setDarkMode={setDarkMode} toggleSidebar={toggleSidebar} />
      <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
      <main className={darkMode === "dark" ? "main-dark" : "main-light"}>
        {children}
      </main>
    </>
  )
}